/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import static Controlador.ControladorActividad2.LeerArchivoGuardado;
import static Controlador.ControladorActividad2.verificarContraseña;
import javax.swing.JOptionPane;

/**
 *
 * @author Victor
 */
public class VistaActividad2 extends javax.swing.JFrame {

    /**
     * Creates new form VistaActividad2
     */
    public VistaActividad2() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
//    public static int VerificarContraseña(String ContrasenaGuardada) {
//
//        String RutaGuardado = "CONTRASENA.txt";
//        String ContraseñaGuardada = LeerArchivoGuardado(RutaGuardado.toString());
//        
//        String ContrasenaIngresada = txtIngresarContraseña.getText();
//
//        if (ContrasenaIngresada.equals(ContraseñaGuardada)) {
//            return 0;
//        } 
//        else {
//            return 1;
//        }
//    }
    
//    public static int verificarContraseña(String contraseñaIngresada, String rutaGuardado) {
//        String contraseñaGuardada = LeerArchivoGuardado(rutaGuardado);
//        if (contraseñaGuardada != null && contraseñaGuardada.equals(contraseñaIngresada)) {
//            return 0;
//        } else {
//            return 1;
//        }
//    }
    
//    public static int VerificarContraseña() {
//        
//        String ContrasenaIngresada = Vista.VistaActividad2.txtIngresarContraseña.getText();
//        String RutaGuardado = "CONTRASENA.txt";
//        String ContraseñaGuardada = LeerArchivoGuardado(RutaGuardado);
//
//        if (ContrasenaIngresada.equals(ContraseñaGuardada)) {
//            return 0;
//        } else {
//            return 1;
//        }
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnVerificar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnGuardarContraseña = new javax.swing.JButton();
        txtIngresarContraseña = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("COMPROBAR CONTRASEÑA");

        jLabel2.setText("Ingrese la contraseña");

        btnVerificar.setText("VERIFICAR");
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });

        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnGuardarContraseña.setText("GUARDAR CONTRASEÑA");
        btnGuardarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarContraseñaActionPerformed(evt);
            }
        });

        txtIngresarContraseña.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIngresarContraseña.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSalir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(btnGuardarContraseña)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVerificar))
                    .addComponent(txtIngresarContraseña))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIngresarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerificar)
                    .addComponent(btnSalir)
                    .addComponent(btnGuardarContraseña))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnGuardarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarContraseñaActionPerformed
        // TODO add your handling code here:
        String ContrasenaIngresada = txtIngresarContraseña.getText().toString();
        String RutaGuardado = "CONTRASENA.txt";
        
        Controlador.ControladorActividad2.GuardarContrasena(ContrasenaIngresada, RutaGuardado);
        System.out.println("Contraseña guardada exitosamente");
        
//        String ContrasenaGuardada = Controlador.ControladorActividad2.LeerArchivoGuardado(RutaGuardado);
//        System.out.println("Contraseña guardada abierta exitosamente");
        
    }//GEN-LAST:event_btnGuardarContraseñaActionPerformed

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed
        // TODO add your handling code here:
//        String ContrasenaAcomprobar = txtIngresarContraseña.getText();
//        
//        int Verificacion = VerificarContraseña(ContrasenaAcomprobar);
//        
//        
//        if(Verificacion == 0){
//            System.out.println("ACCESO PERMITIDO");
//            JOptionPane.showMessageDialog(null, "ACCESO PERMITIDO");
//        }
//        else {
//            System.out.println("ACCESO DENEGADO");
//            JOptionPane.showMessageDialog(null, "ACCESO DENEGADO");
//        }
        
        String ArchivoGuardado = "CONTRASENA.txt";
        String ContrasenaIngresada = txtIngresarContraseña.getText().toString();
        
        Controlador.ControladorActividad2.verificarContraseña(ContrasenaIngresada, ArchivoGuardado);
        
        int verificacion = verificarContraseña(ContrasenaIngresada, ArchivoGuardado);
        
        if (verificacion == 0) {
            System.out.println("ACCESO PERMITIDO");
            JOptionPane.showMessageDialog(null, "ACCESO PERMITIDO");
        } else {
            System.out.println("ACCESO DENEGADO");
            JOptionPane.showMessageDialog(null, "ACCESO DENEGADO");
        }
        
        
    }//GEN-LAST:event_btnVerificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaActividad2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaActividad2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaActividad2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaActividad2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaActividad2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarContraseña;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVerificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtIngresarContraseña;
    // End of variables declaration//GEN-END:variables
}
